### ISSUE TITLE
Use c-hive proxy

### ISSUE THREAD

**Issue by thisismydesign** [c-hive/team-contribution-calendar#25] opened 2019-04-21 21:01 UTC
Our proxy didn't work with a test heroku deployment for some reason, but it should be the default.

**Comment by gomorizsolt** [comment] 2019-04-22 11:17
It's ridiculous, but the issue with the proxy-server was caused by an inadvertently added extra space before the comma separator within the `CORSANYWHERE_WHITELIST` environment variables list.

Closed.

**Comment by thisismydesign** [comment] 2019-04-22 23:31
So is our proxy being used then as default or is it still the other? If so feel free to close again. :)

**Comment by gomorizsolt** [comment] 2019-04-23 06:30
Yes, our proxy is the default one. It seems that it didn't turn out to be fully resolved in my comment above, sorry. :)

**Closed by gomorizsolt** 2019-04-23 06:30 UTC
