### ISSUE TITLE
Cosmetic issues

### ISSUE THREAD

**Issue by thisismydesign** [c-hive/team-contribution-calendar#38] opened 2019-07-05 15:05 UTC
- Note how our squares are not as sharp as GH's (might be caused by https://github.com/c-hive/team-contribution-calendar/issues/37)

![image](https://user-images.githubusercontent.com/3299948/60730803-45422280-9f46-11e9-9dcf-b6664bb3d9a3.png)

vs

![image](https://user-images.githubusercontent.com/3299948/60730831-53903e80-9f46-11e9-923a-4fca2747ec35.png)

- GH uses bigger text for the `X contributions in the last year` text which we could also follow

- GH uses more grey text colos for the colum/row names and less/more text which we could also follow

- spinner resets during loading (possibly related to loading the first user separately)

![Peek 2019-07-05 17-05](https://user-images.githubusercontent.com/3299948/60731139-0f516e00-9f47-11e9-88ac-157e672c6651.gif)

**Comment by thisismydesign** [comment] 2019-07-20 03:38
> Our squares are not as sharp as GH's

This just got fixed on `c-hive.dev` by releasing seemingly unrelated changes. Let's verify it one last time before this issue would be closed.

**Comment by nkapolcs** [comment] 2019-09-16 20:37
> > Our squares are not as sharp as GH's
> 
> This just got fixed on `c-hive.dev` by releasing seemingly unrelated changes. Let's verify it one last time before this issue would be closed.

After the new team-contribution-calendar@v0.1.1 release, I will verify it.

**Comment by thisismydesign** [comment] 2019-09-17 07:39
OK thanks. The other issues might still be relevant though.

**Comment by nkapolcs** [comment] 2019-09-19 20:59
- [x] Note how our squares are not as sharp as GH's (might be caused by https://github.com/c-hive/team-contribution-calendar/issues/37)

![image](https://user-images.githubusercontent.com/3299948/60730803-45422280-9f46-11e9-9dcf-b6664bb3d9a3.png)

vs

![image](https://user-images.githubusercontent.com/3299948/60730831-53903e80-9f46-11e9-923a-4fca2747ec35.png)

**Comment by nkapolcs** [comment] 2019-09-19 21:00
- [ ] GH uses bigger text for the `X contributions in the last year` text which we could also follow
>Kapolcs: In this PR we talk about this https://github.com/c-hive/team-contribution-calendar/pull/45 should I change it now?

**Comment by nkapolcs** [comment] 2019-09-19 21:03
- [ ] GH uses more grey text colos for the colum/row names and less/more text which we could also follow
>Kapolcs: Ok i create a PR for this isuue

**Comment by nkapolcs** [comment] 2019-09-19 21:04
- [x] spinner resets during loading (possibly related to loading the first user separately)

![Peek 2019-07-05 17-05](https://user-images.githubusercontent.com/3299948/60731139-0f516e00-9f47-11e9-88ac-157e672c6651.gif)

>Kapolcs: I this this is working good now

**Comment by thisismydesign** [comment] 2019-09-19 21:45
>  GH uses bigger text for the X contributions in the last year text which we could also follow
> Kapolcs: In this PR we talk about this #45 should I change it now?

Right, was the bigger text causing the jump? Or can you increase the font size to equal GH without re-introducing any issues?

**Comment by thisismydesign** [comment] 2019-09-19 21:54
>  spinner resets during loading (possibly related to loading the first user separately)
> Kapolcs: I this this is working good now

Doesn't seem so on Heroku

![tcc spinner](https://user-images.githubusercontent.com/3299948/65284078-dafa5080-db38-11e9-8c0c-b01edbdb7dd3.gif)

**Comment by gomorizsolt** [comment] 2019-10-30 10:40
Resolved by #51, however, let's make also sure the changes on our site before closing the issue.

**Comment by gomorizsolt** [comment] 2019-11-05 09:20
Verified the changes on our site, closing.

**Closed by gomorizsolt** 2019-11-05 09:20 UTC
